name: build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: install modules
        run: yarn install
      - name: build
        run: yarn build
